[tool.poetry]
name = "unredact"
version = "0.1.0"
description = "This repo contains a script that removes weak redactions from PDFs."
authors = ["Kyle Dent <kdent@seaglass.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
