[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[black]
max-line-length = 80
line-length = 80

[ruff]
fix=true
line-length = 80
target-version = "py311"
select = ["D"]

[ruff.extend-per-file-ignores]
__init__.py = ["D104"]

[ruff.pydocstyle]
convention = "numpy"
