"""Constants used throughout the unredact package."""

DEFAULT_FONT = "Times-Roman"

FONTS = {
    "TimesNewRomanPSMT": "Times-Roman",
    "TimesNewRomanPS-ItalicMT": "Times-Italic",
    "TimesNewRomanPS-BoldItalicMT": "Times-BoldItalic",
    "TimesNewRomanPS-BoldMT": "Times-Bold",
    "ArialMT": "Helvetica",
    "Arial-ItalicMT": "Helvetica-Oblique",
    "Arial-BoldMT": "Helvetica-Bold",
    "Arial-BoldItalicMT": "Helvetica-BoldOblique",
    "CambriaMath": "Times-Roman",
    "Calibri": "Helvetica",
    "Corbel": "Helvetica",
    "CourierNew": "Courier",
    "CourierNewPSMT": "Courier",
    "Arial": "Helvetica",
    "Arial,Bold": "Helvetica-Bold",
    "Arial,BoldItalic": "Helvetica-BoldOblique",
    "QuickTypeII": "Helvetica",
    "QuickTypeII,Italic": "Helvetica-Oblique",
    "QuickTypeII,Bold": "Helvetica-Bold",
    "QuickTypeIICondensed": "Helvetica",
    "QuickTypeIICondensed,Bold": "Helvetica-Bold",
    "QuickTypeIICourierA": "Courier",
    "QuickTypeIIPi": "Helvetica",
    "UniversLTStd-Light": "Helvetica",
    "Univers_LT_Std_45_LightBold": "Helvetica-Bold",
    "Univers_LT_Std_47_Cn_LtBold": "Helvetica-Bold",
    "Univers_LT_Std_47_Cn_Lt": "Helvetica",
    "Univers_LT_Std_57_Cn": "Helvetica",
    "Univers_LT_Std_55": "Helvetica",
    "Univers_LT_67_CondensedBoldBold": "Helvetica-Bold",
    "Verdana": "Helvetica",
    "Wingdings-Regular": "ZapfDingbats",
    "Wingdings2": "ZapfDingbats",
}
