name: Format-and-Fail
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  Black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: psf/black@stable
        with:
          options: --check --verbose
  ISort:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: isort/isort-action@master
        with:
          configuration: --check-only --diff
          requirementsFiles: setup.cfg
  Ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: chartboost/ruff-action@v1
