name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Run lint check
      run: make check

    - name: Run format check
      run: make format

    - name: Run unit tests
      run: make test
